### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [AgoraDesk-LocalMonero/agoradesk-app-foss#251]
https://monitor.f-droid.org/builds/log/co.localmonero.app/1083#site-footer

https://monitor.f-droid.org/builds/log/com.agoradesk.app/1083#site-footer

Could you please take a look? Thanks!

**Comment by sergdeus** [comment]
Hi!
I can see from logs that by some reason it uses
`The current Flutter SDK version is 3.10.2.`
But it should be `Flutter 3.13.0`
The Flutter is set up as a submodule.

Can you please advise what I should fix?

**Comment by linsui** [comment]
Please update the submodule to 3.13.0.

**Comment by sergdeus** [comment]
Thanks, done.

**Comment by linsui** [comment]
The submodule points to an invalid commit. https://github.com/flutter/flutter/tree/7fb354cc3106d0b5a0d6bf4dd47bb65268b00e54

**Comment by sergdeus** [comment]
Sorry, fixed.

**Comment by linsui** [comment]
Thanks!

**Comment by licaon-kter** [comment]
Please bump flutter submodule to 3.16.9 or whatever


ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/6157012926#L841

**Comment by sergdeus** [comment]
Done.
Please check.

**Comment by licaon-kter** [comment]
still 6 months old https://github.com/AgoraDesk-LocalMonero/agoradesk-app-foss/tree/main/submodules

**Comment by sergdeus** [comment]
Thank you. 
Fixed.

**Comment by sergdeus** [comment]
Thank you, fixed.

**Comment by licaon-kter** [comment]
If  I go to https://github.com/AgoraDesk-LocalMonero/agoradesk-app-foss/tree/v1.1.20-fdroid/submodules

and click on `flutter @ 27abbc3`

it takes me to https://github.com/flutter/flutter/tree/27abbc391ea039c84f81b6db85219ffaa4f4f0e6

which says `27abbc391ea039c84f81b6db85219ffaa4f4f0e6 branch of flutter  does not contain the path`

**Comment by sergdeus** [comment]
Heh, submodules is a pian, sorry for that.
Fixed.

**Comment by licaon-kter** [comment]
Thanks

**Comment by linsui** [comment]
https://gitlab.com/linsui/fdroiddata/-/jobs/6195145514 It still fails.

**Comment by sergdeus** [comment]
Completely re-instantiated (removed and init form the scratch) flutter submodule.
Pushed.
Can you please try again?

**Comment by linsui** [comment]
I thought the error is not caused by the flutter version.

```
lib/core/widgets/branded/button_square_icon.dart:36:15: Error: No named parameter with the name 'primary'.
              primary: context.colS3,
              ^^^^^^^
```

Is this expected?

```
2024-02-17 08:15:20,340 INFO: Removing usual suspect 'com.google.android.gms' at .pub-cache/hosted/pub.dev/google_api_availability_android-1.0.1/android/build.gradle
2024-02-17 08:15:20,340 INFO: Removing usual suspect 'play-services' at .pub-cache/hosted/pub.dev/google_api_availability_android-1.0.1/android/build.gradle
```

**Comment by sergdeus** [comment]
Hmm, this is just a warning, it shouldn't lead to an error. On the main, it works well.

But ok, fixed, pushed.

Please check when you have time.

Thanks!

**Comment by linsui** [comment]
https://gitlab.com/linsui/fdroiddata/-/jobs/6195705007 Still fails...

**Comment by sergdeus** [comment]
Шt was a package outside of the application.
Updated the package.
Pushed.

**Comment by sergdeus** [comment]
It was a package outside of the application.
Updated the package.
Pushed.

**Comment by linsui** [comment]
Did you update the flutter submodule to a too new version? It should be checkout to the same version you use locally. Looks like the version finally matches and now we need to remove the non-free lib.

**Comment by sergdeus** [comment]
Yes, I pulled a new version today.
I don't use submodule locally or for the CI, only for the F-Droid.

Hmm, what are non-free lib?

**Comment by linsui** [comment]
```
2024-02-17 08:15:20,340 INFO: Removing usual suspect 'com.google.android.gms' at .pub-cache/hosted/pub.dev/google_api_availability_android-1.0.1/android/build.gradle
2024-02-17 08:15:20,340 INFO: Removing usual suspect 'play-services' at .pub-cache/hosted/pub.dev/google_api_availability_android-1.0.1/android/build.gradle
```

google_api_availability_android uses GMS.

**Comment by sergdeus** [comment]
Removed. Pushed.

**Comment by linsui** [comment]
Thanks!

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/jobs/6665140735 The in_app_review lib is not removed from the fdroid branch.

**Comment by sergdeus** [comment]
Thank you.
Fixed, pushed.

**Comment by licaon-kter** [comment]
@sergdeus so which commits should we use?

**Comment by linsui** [comment]
Thanks!

**Comment by sergdeus** [comment]
Thank you!

**Comment by licaon-kter** [comment]
https://gitlab.com/fdroid/fdroiddata/-/jobs/6965542508#L952 again...

Flutter submodule is 2 months old, not sure if it matters

**Comment by sergdeus** [comment]
Hi!
Can you please check again, updated.

**Comment by licaon-kter** [comment]
Thanks
